### ISSUE TITLE
Files uploaded to /wp-content/uploads/

### ISSUE THREAD

**Issue by Ben-Carter-CancerTools** [alexandru-burca/woocommerce-gateway-purchase-order-file#1]
Hi,

Firstly - thanks for this it works very well! However I have just discovered that PO files are uploaded to /wp-content/uploads/ which is publicly accessible. Is there any way to change where the files are uploaded to?

Many thanks,

Ben

**Comment by alexandru-burca** [comment]
Hi there, you can try updating this [method](https://github.com/alexandru-burca/woocommerce-gateway-purchase-order-file/blob/34f9a1aa956e10dd0647545a0b81b8f0c5fc6ef4/public/class-woocommerce-gateway-purchase-order-file-public.php#L95 ).
I used [wp_upload_bits](https://developer.wordpress.org/reference/functions/wp_upload_bits/) to upload the file, it creates a file in the upload folder. 
So instead of using this WP function try using a default PHP function, like for example [move_uploaded_file](https://www.php.net/manual/en/function.move-uploaded-file.php) and change the destination folder. However, the link will still be public accessible, you will change only the destination folder. And this makes sense because the file URL is attached to the default email body and must be public accessible.
